const c=window.SITE_CONTENT,$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),txt=(s,v)=>$(s).textContent=v;
txt('[data-hero-kicker]',c.hero.kicker);$('[data-hero-title]').innerHTML=c.hero.title;txt('[data-hero-copy]',c.hero.text);$('[data-hero-image]').src=c.hero.image;txt('[data-about-title]',c.about.title);txt('[data-about-text]',c.about.text);txt('[data-about-note]',c.about.note);txt('[data-artist-name]',c.artist.name);txt('[data-artist-text]',c.artist.text);$('[data-artist-image]').src=c.artist.image;txt('[data-address]',c.contact.address);txt('[data-city]',c.contact.city);txt('[data-email]',c.contact.email);txt('[data-year]',new Date().getFullYear());
$$('[data-email-link]').forEach(e=>e.href=`mailto:${c.contact.email}`);$$('[data-instagram-link]').forEach(e=>e.href=c.contact.instagram);$('[data-map-link]').href=c.contact.map;$('[data-hours]').innerHTML=c.contact.hours.map(x=>`<li>${x}</li>`).join('');$('[data-steps]').innerHTML=c.steps.map(x=>`<li><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></li>`).join('');
const renderOptionalArtist=(key,prefix)=>{const data=c[key]||{},section=$(`[data-${prefix}-section]`);section.hidden=data.enabled!==true;if(section.hidden)return;txt(`[data-${prefix}-label]`,data.label||'Artist');txt(`[data-${prefix}-name]`,data.name||'Name folgt');txt(`[data-${prefix}-text]`,data.text||'');const dates=$(`[data-${prefix}-dates]`);dates.textContent=data.dates||'';dates.hidden=!data.dates;const image=$(`[data-${prefix}-image]`);image.src=data.image||'images/logo(transparent).png';image.alt=data.imageAlt||`Porträt von ${data.name||'Artist'}`;image.parentElement.classList.toggle('artist-placeholder',image.src.includes('logo(transparent)'));const instagram=$(`[data-${prefix}-instagram]`);instagram.href=data.instagram||'#';instagram.hidden=!data.instagram;const email=$(`[data-${prefix}-email]`);if(email){email.href=`mailto:${data.email||c.contact.email}`}};
renderOptionalArtist('secondArtist','second-artist');renderOptionalArtist('guestArtist','guest-artist');
const itemData=x=>Array.isArray(x)?{type:'image',src:x[0],alt:x[1]}:{type:x.type||'image',...x};
const renderGallery=(selector,items)=>{const gallery=$(selector);gallery.innerHTML=items.map(raw=>{const x=itemData(raw);const previewTime=x.previewTime===undefined?0.1:x.previewTime;const media=x.type==='video'?`<video src="${x.src}" data-preview-time="${previewTime}" aria-label="${x.alt}" muted loop playsinline preload="metadata"></video><span class="video-badge" aria-hidden="true">▶</span>`:`<img src="${x.src}" alt="${x.alt}" loading="lazy" decoding="async">`;return `<button type="button" data-src="${x.src}" data-type="${x.type}" data-alt="${x.alt}" aria-label="${x.alt} öffnen">${media}</button>`}).join('');gallery.querySelectorAll('video').forEach(video=>{const previewTime=Number(video.dataset.previewTime)||0.1,showPreview=()=>{video.pause();if(video.readyState>=1)video.currentTime=Math.min(previewTime,Math.max(0,video.duration-.01))},play=()=>video.play().catch(()=>{});if(video.readyState>=1)showPreview();else video.addEventListener('loadedmetadata',showPreview,{once:true});video.closest('button').addEventListener('mouseenter',play);video.closest('button').addEventListener('focus',play);video.closest('button').addEventListener('mouseleave',showPreview);video.closest('button').addEventListener('blur',showPreview)});gallery.onclick=e=>{const b=e.target.closest('button');if(!b)return;openMedia(b.dataset)}};
const lightbox=$('[data-lightbox]'),lightboxImage=$('[data-lightbox-image]'),lightboxVideo=$('[data-lightbox-video]');const openMedia=data=>{lightboxImage.hidden=data.type==='video';lightboxVideo.hidden=data.type!=='video';if(data.type==='video'){lightboxVideo.src=data.src;lightboxVideo.setAttribute('aria-label',data.alt);lightboxVideo.play().catch(()=>{})}else{lightboxImage.src=data.src;lightboxImage.alt=data.alt}lightbox.showModal()};$('[data-close-lightbox]').onclick=()=>lightbox.close();lightbox.addEventListener('close',()=>{lightboxVideo.pause();lightboxVideo.removeAttribute('src');lightboxVideo.load()});
const shuffled=items=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const loadGalleries=async()=>{try{const response=await fetch('galleries.json',{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const galleries=await response.json();const options=c.galleryOptions||{};renderGallery('[data-venue-gallery]',options.randomVenue?shuffled(galleries.venue):galleries.venue);renderGallery('[data-works-gallery]',options.randomWorks?shuffled(galleries.works):galleries.works)}catch(error){console.error('Galerien konnten nicht geladen werden:',error);$$('[data-venue-gallery],[data-works-gallery]').forEach(gallery=>gallery.innerHTML='<p class="gallery-error">Galerie konnte nicht geladen werden.</p>')}};loadGalleries();
const mb=$('[data-menu-button]'),menu=$('[data-menu]');mb.onclick=()=>{let open=menu.classList.toggle('open');mb.setAttribute('aria-expanded',open);document.body.classList.toggle('menu-open',open)};menu.onclick=()=>{menu.classList.remove('open');mb.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};
$$('[data-reveal]').forEach(e=>e.classList.add('reveal'));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});$$('[data-reveal]').forEach(e=>io.observe(e));
const legal={
  impressum:`<h2>Impressum</h2>
    <h3>Angaben gemäß § 5 DDG</h3>
    <p>Nadelwerk Tattoo<br>Inhaber: Frank Dietzel<br>Rheingasse 14<br>78462 Konstanz</p>
    <h3>Kontakt</h3>
    <p>E-Mail: <a href="mailto:${c.contact.email}">${c.contact.email}</a></p>
    <h3>Haftung für Inhalte</h3>
    <p>Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Wir sind jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden entsprechender Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>
    <h3>Haftung für Links</h3>
    <p>Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zu diesem Zeitpunkt nicht erkennbar. Eine permanente inhaltliche Kontrolle ist ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>
    <h3>Urheberrecht</h3>
    <p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors oder Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit Inhalte nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>`,
  datenschutz:`<h2>Datenschutz</h2><h3>Verantwortlicher</h3><p>Nadelwerk Tattoo, Frank Dietzel, Rheingasse 14, 78462 Konstanz<br>${c.contact.email}</p><h3>Server-Logfiles</h3><p>Der Hosting-Anbieter kann technisch notwendige Zugriffsdaten verarbeiten. Grundlage ist Art. 6 Abs. 1 lit. f DSGVO.</p><h3>Kontaktaufnahme</h3><p>Bei einer E-Mail verarbeiten wir Ihre Angaben zur Bearbeitung der Anfrage und löschen sie, sobald keine gesetzlichen Pflichten mehr entgegenstehen.</p><h3>Externe Links</h3><p>Instagram und Google Maps werden erst aufgerufen, wenn Sie den jeweiligen Link anklicken.</p><h3>Ihre Rechte</h3><p>Sie haben insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch und Beschwerde bei einer Aufsichtsbehörde.</p><small>Stand: August 2026. Diese Vorlage ersetzt keine Rechtsberatung.</small>`
};
const ld=$('[data-legal-dialog]');$$('[data-dialog]').forEach(b=>b.onclick=()=>{$('[data-legal-content]').innerHTML=legal[b.dataset.dialog];ld.showModal()});$('[data-close-dialog]').onclick=()=>ld.close();[ld,lightbox].forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});
